remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
title: PPS-22-23-plague
description: "Project of the course of PPS-22-23: plague"
nav:
  - Retrospettiva: 06_Retrospettiva.md
github:
  private: false
  license:
    name: MIT
  repository_url: "https://github.com/FilippoVenturini8/PPS-22-plague"
