theme: minima
title: PPS-22-23-plague
description: "Project of the course of PPS-22-23: plague"
github:
  private: false
  license:
    name: MIT
  repository_url: "https://github.com/FilippoVenturini8/PPS-22-plague"
